const SERVER = "http://localhost:8080";

const GET_MEDICI_SUCCES = "GET_MEDICI_SUCCES";
const GET_MEDICI_ERROR = "GET_MEDICI_ERROR";

const ADD_MEDIC_SUCCES = "ADD_MEDIC_SUCCES";
const ADD_MEDIC_ERROR = "ADD_MEDIC_ERROR";

export {
  ADD_MEDIC_SUCCES,
  ADD_MEDIC_ERROR,
  GET_MEDICI_SUCCES,
  GET_MEDICI_ERROR,
  SERVER,
};
